baseURL = "https://stillru.github.io"
languageCode = "en-us"
theme = "still-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 2

#  [[menu.header]]
#  name = "Portfolio"
#  URL = "#portfolio"
#  weight = 3

  [[menu.header]]
  name = "Experience"
  URL = "#experience"
  weight = 4

  [[menu.header]]
  name = "Blog"
  URL = "/blog"
  weight = 5

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 6

  [[menu.footer]]
  name = "About"
  URL = "#about"
  weight = 2

 # [[menu.footer]]
 # name = "Portfolio"
 # URL = "#portfolio"
 # weight = 3

 # [[menu.footer]]
 # name = "Contact"
 # URL = "#contact"
 # weight = 4


[params]

  sections = ["showcase", "about", "skills", "education", "experience", "contact", "newsletter"]

  homepageExperienceCount = 4

  [params.google_analytics]
      code = "UA-XXXXX-Y"
      enabled = true
  [params.google_tag_manager]
      code = "G-CFCF17QFBJ"
      enabled = true
  
  [params.logo]
    text1 = "Stepan"
    text2 = "Illichevskii"

  [params.footer]
      copyright = "© Stepan Illichevsky. Free Hugo theme by Adrián Moreno Peña."
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"
